Repository KaizenGirl1111/GSGrihSangini, pull requests merged in 2022-05, with the labels that each got.

#59 hover effect added
  src/Components/App/NavigationBar/NavigationBar.css
  src/Components/App/NavigationBar/NavigationBar.jsx
Labels: new feature, advanced, GSSoC22, Level3

#57 confirm password field added
  src/Components/App/Workersignup.jsx
Labels: GSSoC22, Level3

#55 show-hide password added in worker-login page
  src/Components/App/Workerlogin.jsx
Labels: GSSoC22, Level3

#47 New user and Already registered button added in login and signup page
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
Labels: GSSoC22, Level3

#52 Backend(Worker)
  backend/index.js
  backend/model/Worker.js
  backend/routes/worker.js
Labels: GSSoC22, Level3

#40 NavigationBar and Footer added in Login Page
  src/Components/App/Login.jsx
Labels: GSSoC22, Level2

#71 States used inside Signup Page
  src/Components/App/Signup.jsx
Labels: new feature, advanced, GSSoC22, Level3

#69 States added in Login Page
  src/Components/App/Login.jsx
Labels: new feature, advanced, GSSoC22, Level3

#64 MobileNoFieldinWorkerLoginForm
  src/Components/App/Workerlogin.jsx
Labels: help wanted, GSSoC22, Level3

#82 new worker option added in workerlogin page
  src/Components/App/Workerlogin.jsx
Labels: new feature, advanced, GSSoC22, Level3

#81 Already registered worker option added in workersignup page
  src/Components/App/Workersignup.jsx
Labels: new feature, advanced, GSSoC22, Level3

#80 New user option added in login page
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
Labels: new feature, GSSoC22, Level2

#76 Contact us page added
  package-lock.json
  src/Components/App/App.js
  src/Components/App/Contactus.js
  src/Components/App/NavigationBar/NavigationBar.jsx
Labels: new feature, GSSoC22, Level3

#94 Signup page UI
  src/Components/App/Signup.jsx
  src/Components/App/signup.css
Labels: GSSoC22, Level3

#92 UI of login page modified
  package-lock.json
  package.json
  src/Components/App/Login.jsx
  src/Components/App/login.css
Labels: GSSoC22, Level3

#84 state-register-worker
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: GSSoC22, Level3

#85 SchemaModified
  backend/model/User.js
Labels: GSSoC22, Level3

#99 Improved UI of worker-signup page
  src/Components/App/Signup.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: intermediate, help wanted, GSSoC22, Level2

#90 States added in Contact us page
  src/Components/App/Contactus.js
Labels: intermediate, GSSoC22, Level2

#107 Made the ScrollToTop button dynamic
  src/Components/App/Home.jsx
Labels: intermediate, new feature, GSSoC22, Level2

#103 UI improved for worker login page
  src/Components/App/Workerlogin.jsx
Labels: GSSoC22, Level2

#102 styled-home-page
  package-lock.json
  package.json
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/Containers/ServiceContainer/ServiceContainer.jsx
  src/Components/App/NavigationBar/NavigationBar.css
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: new feature, help wanted, GSSoC22, Level3

#116 AboutUsPage
  src/Components/App/AboutUs.css
  src/Components/App/AboutUs.js
  src/Components/App/App.js
  src/Components/App/NavigationBar/NavigationBar.css
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: new feature, GSSoC22, Level3

#117 readme_update
  README.md
Labels: documentation, help wanted, good first issue, GSSoC22, Level2

#113 WorkerFormEnabled
  backend/package.json
  package-lock.json
  package.json
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: help wanted, advanced, GSSoC22, Level3

#112 Home button added
  package-lock.json
  src/Components/App/NavigationBar/NavigationBar.css
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: help wanted, good first issue, GSSoC22, Level2

#119 added Google Authentication
  package-lock.json
  package.json
  src/Components/App/Signup.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/signup.css
  src/firebase-config.js
Labels: advanced, GSSoC22, Level3

#131 Frontend and Backend connected
  package-lock.json
  package.json
Labels: GSSoC22, Level3

#130 FormsPushedDown
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/login.css
  src/Components/App/signup.css
  src/Components/App/workerlogin.css
  src/Components/App/workersignup.css
Labels: GSSoC22, Level2

#129 SchemaModifiedCardsRendered
  backend/model/Worker.js
  package-lock.json
  src/Components/App/App.js
Labels: GSSoC22, Level2

#133 SearchFromDummy
  src/Components/App/App.js
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Worker.js
Labels: GSSoC22, Level3

#138 Welcome email sent to user just after signing up
  .env
  backend/mailer/mailer.js
  backend/package.json
  backend/routes/user.js
Labels: new feature, advanced, GSSoC22, Level3

#144 JWT auth added for users authentication
  backend/middleware/auth.js
  backend/package.json
  backend/routes/user.js
  package-lock.json
  package.json
Labels: GSSoC22, Level3

#140 Added Email Authentication
  src/Components/App/Login.jsx
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Signup.jsx
Labels: new feature, advanced, GSSoC22, Level3

#150 an eye button added in worker login page
  src/Components/App/Workerlogin.jsx
  src/Components/App/login.css
Labels: intermediate, GSSoC22, Level2

#148 Token verification and redirecting to homepage after successful signup
  backend/routes/user.js
  src/Components/App/Login.jsx
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Signup.jsx
Labels: GSSoC22, Level3

#146 Find worker visible only after log in
  backend/routes/user.js
  src/Components/App/Login.jsx
  src/Components/App/NavigationBar/NavigationBar.jsx
Labels: new feature, GSSoC22, Level3

#121 Pathway to ClientRequest
  backend/db/mongoose.js
  backend/model/Worker.js
  backend/package.json
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/ClientRequest/ClientRequest.css
  src/Components/App/ClientRequest/ClientRequest.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: GSSoC22, Level3

#154 All errors resolved. Project woking smoothly.
  src/Components/App/AboutUs.css
  src/Components/App/Workers/WorkerCard.css
  src/Components/App/Workers/WorkerCard.js
Labels: new feature, help wanted, good first issue, GSSoC22, Level2

#157 UserSchema modified
  backend/model/User.js
  backend/routes/user.js
  package-lock.json
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: GSSoC22, Level3

#165 Frontend and Backend for forgot password got connected
  backend/mailer/mailer.js
  backend/routes/user.js
  src/Components/App/App.js
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/forgotPassword.js
Labels: new feature, help wanted, GSSoC22, Level3

#166 Password modified and saved inside database and link also gets expired in 20min
  backend/mailer/mailer.js
  backend/model/User.js
  backend/routes/user.js
  package-lock.json
  src/Components/App/ResetPassword.js
  src/Components/App/Signup.jsx
Labels: new feature, help wanted, advanced, GSSoC22, Level3

#167 LogoutButtonAdded
  package-lock.json
  src/Components/App/NavigationBar/NavigationBar.css
  src/Components/App/NavigationBar/NavigationBar.jsx
Labels: good first issue, GSSoC22, Level1

#173 Eye button inside login page
  src/Components/App/Login.jsx
Labels: new feature, GSSoC22, Level1

#171 GS Sos Page added
  src/Components/App/App.js
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/SosPage.css
  src/Components/App/SosPage.js
Labels: new feature, help wanted, good first issue, GSSoC22, Level2

#177 signup with google fixed and added
  src/Components/App/Signup.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/signup.css
Labels: GSSoC22, Level2

#176 Toast messages generated.
  backend/mailer/mailer.js
  backend/routes/user.js
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/forgotPassword.js
  src/Components/toast/toast.js
Labels: GSSoC22, Level3

#181 About us section added
  src/Components/App/Containers/ServiceContainer/ServiceContainer.css
  src/Components/App/Containers/ServiceContainer/ServiceContainer.jsx
Labels: GSSoC22, Level2

#195 github icon added with link added in footer
  backend/model/Worker.js
  backend/routes/user.js
  backend/routes/worker.js
  package-lock.json
  src/Components/App/AboutUs.js
  src/Components/App/Footer/Footer.jsx
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
  src/Components/App/SosPage.css
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
Labels: GSSoC22, Level1
