Repository KaizenGirl1111/GSGrihSangini, pull requests merged in 2022-04, with the labels that each got.

#24 BackendEndpoints
  backend/index.js
  backend/model/User.js
  backend/package.json
  backend/routes/user.js
Labels: new feature, advanced, GSSoC22, Level3

#27 ContactByEmailEnabled
  package-lock.json
  src/Components/App/NavigationBar/NavigationBar.jsx
Labels: help wanted, advanced, GSSoC22, Level3

#16 Create LICENSE.md
  LICENSE.md
Labels: good first issue, GSSoC22, Level2

#45 Hover effect aded in service container
  src/Components/App/Containers/ServiceContainer/ServiceCard/ServiceCard.css
Labels: bug, new feature, help wanted, GSSoC22, Level2

#36 Confirm password field added
  package-lock.json
  src/Components/App/Login.jsx
  src/Components/App/Signup.jsx
  src/Components/App/login.css
Labels: intermediate, new feature, GSSoC22, Level2

#43 Worker-Frontend
  backend/model/Worker.js
  src/Components/App/App.js
  src/Components/App/NavigationBar/NavigationBar.jsx
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/workerlogin.css
  src/Components/App/workersignup.css
Labels: intermediate, new feature, GSSoC22, Level3

#38 Subject and Favicon added
  public/favicon.ico
  public/index.html
  src/Components/App/App.js
Labels: advanced, GSSoC22, Level3

#42 NavigationBar and Footer added in Signup Page
  src/Components/App/Signup.jsx
Labels: GSSoC22, Level2

#51 Project Hosted in Vercel
  README.md
Labels: intermediate, good first issue, GSSoC22, Level2

#50 NavbarAndFooterToComponents
  package-lock.json
  src/Components/App/Workerlogin.jsx
  src/Components/App/Workersignup.jsx
  src/Components/App/workerlogin.css
Labels: help wanted, GSSoC22, Level2
